title: Notes
description: >-
  Notes, Posts, mostly Drafts.

url: ""
baseurl: "/notes"

author:
  name: Thomas Tych
  url:

github: "ttych/notes"
gitlab: "ttych/notes"

comments: true
disqus: ''


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

include:
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tmp/


permalink: /:year/:month/:title

paginate: 8
paginate_path: "/page:num/"
paginate_around: 2


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      show_excerpt: true
      layout: post
      author: Thomas Tych
      type: post
