title: Notes
description: >-
  Notes, Posts, mostly Drafts.

url: ""
baseurl: "/notes"

github: "ttych/notes"
gitlab: "ttych/notes"

comments: true
isso: ''
disqus: ''


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tmp/


permalink: /:year/:month/:title
paginate: 8


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      show_excerpt: true
      layout: article
      author: Thomas Tych
